import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import dynamic from 'next/dynamic';

import FrontHeader from '@/components/widget/front-header';

const ThemeProvider = dynamic(() => import('@/components/widget/theme-provider'), { ssr: false });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <FrontHeader></FrontHeader>

                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
